version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:${SOFTWARE_VERSION_TAG}
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data:/usr/share/opensearch/data
    ports:
      - 172.17.0.1:9200:9200
      - 172.17.0.1:9600:9600
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:${SOFTWARE_VERSION_TAG}
    container_name: opensearch-dashboards
    ports:
      - 172.17.0.1:5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    networks:
      - opensearch-net
volumes:
  opensearch-data1:
networks:
  opensearch-net: